<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>wORM</title>

    <!-- ** CSS ** -->
    <!-- base library -->
    <link rel="stylesheet" type="text/css" href="<?=BASE_URL?>/js/ext/resources/css/ext-all.css" />
    <link rel="stylesheet" type="text/css" href="<?=BASE_URL?>/js/ext/ux/css/CenterLayout.css" />
    <link rel="stylesheet" type="text/css" href="<?=BASE_URL?>/css/general.css">
    <script type="text/javascript" src="<?=BASE_URL?>/js/ext/adapter/ext/ext-base.js"></script>
    <script type="text/javascript" src="<?=BASE_URL?>/js/jquery.js"></script>    
    <script type="text/javascript" src="<?=BASE_URL?>/js/ext/adapter/jquery/ext-jquery-adapter.js"></script>
    <script type="text/javascript" src="<?=BASE_URL?>/js/ext/ext-all.js"></script>
    <script type="text/javascript" src="<?=BASE_URL?>/js/ext/ux/CenterLayout.js"></script>
    <script type="text/javascript" src="<?=BASE_URL?>/js/ext/ux/TabCloseMenu.js"></script>
    <script type="text/javascript" src="<?=BASE_URL?>/js/ext/ux/layout.columnfit.js"></script>

    <script type="text/javascript" src="<?=BASE_URL?>/js/general.js"></script>
    
    <script type="text/javascript" src="<?=BASE_URL?>/js/codepress/codepress.js"></script>
    <script type="text/javascript">
    	var BASE_URL = "<?=BASE_URL?>";
    </script>
</head>
<body>
    <div id="header"><h1>wORM</h1></div>
    <div style="display:none;">

        <!-- Start page content -->
        <div id="welcome">
            <div style="margin-left:100px;">
                <h2>Welcome!</h2>
            </div>
        </div>
    </div>
</body>
</html>
