<br/>
<br/>
<table class="default_text" width="100%" cellpadding="0" cellspacing="0" border="0" style="empty-cells: show;">
	<tr>
		<td width="50%" align="right" style="padding-right:5px; border-right: 1px #ccc solid;" >
			name
		</td>
		<td width="50%" align="left" style="padding-left:5px; font-weight: bold;" >
			<?=$this->host["name"]?>
		</td>
	</tr>
	<tr>
		<td width="50%" align="right" style="padding-right:5px; border-right: 1px #ccc solid;" >
			host
		</td>
		<td width="50%" align="left" style="padding-left:5px; font-weight: bold;" >
			<?=$this->host["host"]?>
		</td>
	</tr>
	<tr>
		<td width="50%" align="right" style="padding-right:5px; border-right: 1px #ccc solid;" >
			port
		</td>
		<td width="50%" align="left" style="padding-left:5px; font-weight: bold;" >
			<?=$this->host["port"]?>
		</td>
	</tr>
	<tr>
		<td width="50%" align="right" style="padding-right:5px; border-right: 1px #ccc solid;" >
			user
		</td>
		<td width="50%" align="left" style="padding-left:5px; font-weight: bold;" >
			<?=$this->host["user"]?>
		</td>
	</tr>
	<tr>
		<td width="50%" align="right" style="padding-right:5px; border-right: 1px #ccc solid;" >
			password
		</td>
		<td width="50%" align="left" style="padding-left:5px; font-weight: bold;" >
			******
		</td>
	</tr>
	<tr>
		<td width="50%" align="right" style="padding-right:5px; border-right: 1px #ccc solid;" >
			schema
		</td>
		<td width="50%" align="left" style="padding-left:5px; font-weight: bold;" >
			<?=$this->host["schema"]?>
		</td>
	</tr>
	<tr>
		<td width="50%" align="right" style="padding-right:5px; border-right: 1px #ccc solid;" >
			charset
		</td>
		<td width="50%" align="left" style="padding-left:5px; font-weight: bold;" >
			<?=$this->host["charset"]?>
		</td>
	</tr>
	<tr>
		<td width="50%" align="right" style="padding-right:5px; border-right: 1px #ccc solid;" >
			connector
		</td>
		<td width="50%" align="left" style="padding-left:5px; font-weight: bold;" >
			<?=$this->host["connector"]?>
		</td>
	</tr>
	<tr>
		<td width="50%" align="right" style="padding-right:5px; border-right: 1px #ccc solid;" >
			unique name
		</td>
		<td width="50%" align="left" style="padding-left:5px; font-weight: bold;" >
			<?=$this->host["unique_name"]?>
		</td>
	</tr>
	<tr>
		<td align="center" width="100%" colspan="2">
		&nbsp;
		</td>
	</tr>
	<tr>
		<td align="center" width="100%" colspan="2">
			<table cellspacing="0" class="x-btn   x-btn-noicon" id="ext-comp-1008" style="width: 75px;">
				<tbody class="x-btn-small x-btn-icon-small-left">
					<tr>
						<td class="x-btn-tl">
							<i>&nbsp;</i>
						</td>
						<td class="x-btn-tc">
						</td>
						<td class="x-btn-tr">
							<i>&nbsp;</i>
						</td>
					</tr>
					<tr>
						<td class="x-btn-ml">
							<i>&nbsp;</i>
						</td>
						<td class="x-btn-mc">
							<em unselectable="on" class="">
							<button type="button" id="ext-gen58" class=" x-btn-text" onClick=' var tab = tabManager.createTab("tab_<?=$this->host["id"]?>", "<?=$this->host["name"]?>");  	tab.show();'>Use This Connection</button>
							</em>
						</td>
						<td class="x-btn-mr">
							<i>&nbsp;</i>
						</td>
					</tr>
					<tr>
						<td class="x-btn-bl">
							<i>&nbsp;</i>
						</td>
						<td class="x-btn-bc"></td>
						<td class="x-btn-br">
							<i>&nbsp;</i>
						</td>
					</tr>
				</tbody>
			</table>
		</td>
	</tr>
</table>